<?php

namespace ShopeePhp\Traits;

trait Sign
{
    public function getSign(): string
    {
        return $this->parameters['sign'];
    }

    /**
     * Signature generated by partner_id, api path, timestamp, access_token,
     *  shop_id and partner_key via HMAC-SHA256 hashing algorithm. More
     *  details:
     * https://open.shopee.com/documents?module=87&type=2&id=58version=2
     *
     * @param string $name
     * @return $this
     */
    public function setSign(string $name)
    {
        $this->parameters['sign'] = $name;

        return $this;
    }
}
